### ISSUE TITLE
Wrong url in NPM

### ISSUE THREAD

**Issue by koxu1996** [mathiasbynens/wtf-8#3]
I am unable to install `socket.io` using `composer`, because [NPM page](https://www.npmjs.com/package/wtf-8) point to non-existing link `https://github.com/mathiasbynens/wtf-8.js`, which should be `https://github.com/mathiasbynens/wtf-8` instead. Could you fix it?

**Comment by mathiasbynens** [comment]
Fixed by publishing v1.0.1.
